- change spaces to tabs.

diff --git a/arm-image-installer b/arm-image-installer
--- a/arm-image-installer
+++ b/arm-image-installer
@@ -33,94 +33,94 @@ Example: $(basename ${0}) --image=Fedora-Rawhide.xz --target=Bananapi --media=/d
 # and valid targets.
 DIR=$(dirname $0)
 if [ -d "/usr/share/arm-image-installer/boards.d" ]; then
-        BOARDDIR="/usr/share/arm-image-installer/boards.d"
+	BOARDDIR="/usr/share/arm-image-installer/boards.d"
 	DOC_DIR="/usr/share/doc/fedora-arm-installer/"
 else
-        DIR=$(dirname $0)
-        BOARDDIR="${DIR}/boards.d"
+	DIR=$(dirname $0)
+	BOARDDIR="${DIR}/boards.d"
 	DOC_DIR="${DIR}/"
 fi
 
 # check the args
 while [ $# -gt 0 ]; do
-        case $1 in
-                --debug)
-                        set -x
-                        ;;
-                -h|--help)
-                        usage
-                        exit 0
-                        ;;
-                --target*)
-                        if echo $1 | grep '=' >/dev/null ; then
-                                TARGET=$(echo $1 | sed 's/^--target=//')
-                        else
-                                TARGET=$2
-                                shift
-                        fi
-                        ;;
-                --image*)
-                        if echo $1 | grep '=' >/dev/null ; then
-                                IMAGE=$(echo $1 | sed 's/^--image=//')
-                        else
-                                IMAGE=$2
-                                shift
-                        fi
-                        ;;
-                --media*)
-                        if echo $1 | grep '=' >/dev/null ; then
-                                MEDIA=$(echo $1 | sed 's/^--media=//')
-                        else
-                                MEDIA=$2
-                                shift
-                        fi
-                        ;;
-                --addkey*)
-                        if echo $1 | grep '=' >/dev/null ; then
-                                SSH_KEY=$(echo $1 | sed 's/^--addkey=//')
-                        else
-                                SSH_KEY=$2
-                                shift
-                        fi
-                        ;;
-                --selinux*)
-                        if echo $1 | grep '=' >/dev/null ; then
-                                SELINUX=$(echo $1 | sed 's/^--selinux=//')
-                        else
-                                SELINUX=$2
-                                shift
-                        fi
-                        ;;
-                --norootpass)
-                        NOROOTPASS=1
-                        ;;
-                --resizefs)
-                        RESIZEFS=1
-                        ;;
-                --addconsole)
-                        CONSOLE=1
+	case $1 in
+		--debug)
+			set -x
+			;;
+		-h|--help)
+			usage
+			exit 0
+			;;
+		--target*)
+			if echo $1 | grep '=' >/dev/null ; then
+				TARGET=$(echo $1 | sed 's/^--target=//')
+			else
+				TARGET=$2
+				shift
+			fi
+			;;
+		--image*)
+			if echo $1 | grep '=' >/dev/null ; then
+				IMAGE=$(echo $1 | sed 's/^--image=//')
+			else
+				IMAGE=$2
+				shift
+			fi
+			;;
+		--media*)
+			if echo $1 | grep '=' >/dev/null ; then
+				MEDIA=$(echo $1 | sed 's/^--media=//')
+			else
+				MEDIA=$2
+				shift
+			fi
+			;;
+		--addkey*)
+			if echo $1 | grep '=' >/dev/null ; then
+				SSH_KEY=$(echo $1 | sed 's/^--addkey=//')
+			else
+				SSH_KEY=$2
+				shift
+			fi
+			;;
+		--selinux*)
+			if echo $1 | grep '=' >/dev/null ; then
+				SELINUX=$(echo $1 | sed 's/^--selinux=//')
+			else
+				SELINUX=$2
+				shift
+			fi
+			;;
+		--norootpass)
+			NOROOTPASS=1
+			;;
+		--resizefs)
+			RESIZEFS=1
+			;;
+		--addconsole)
+			CONSOLE=1
 			;;
 		--blacklistvc4)
 			FIX_RPI=1	
-                        ;;
+			;;
 		--supported)
-                        cat $DOC_DIR/SUPPORTED-BOARDS
-                        exit 0
-                        ;;
-                --version)
-                        echo "$(basename ${0})-"$VERSION""
-                        exit 0
-                        ;;
-                -y)
-                        NOASK=1
-                        ;;
-                *)
-                        echo "$(basename ${0}): Error - ${1}"
-                        usage
-                        exit 1
-                        ;;
-        esac
-        shift
+			cat $DOC_DIR/SUPPORTED-BOARDS
+			exit 0
+			;;
+		--version)
+			echo "$(basename ${0})-"$VERSION""
+			exit 0
+			;;
+		-y)
+			NOASK=1
+			;;
+		*)
+			echo "$(basename ${0}): Error - ${1}"
+			usage
+			exit 1
+			;;
+	esac
+	shift
 done
 
 contains() {
@@ -128,46 +128,46 @@ contains() {
     substring="$2"
     if test "${string#*$substring}" != "$string"
     then
-        return 0    # $substring is in $string
+	return 0    # $substring is in $string
     else
-        return 1    # $substring is not in $string
+	return 1    # $substring is not in $string
     fi
 }
 
 # ensure sudo user
 if [ "$(whoami)" != "root" ] ; then
-        echo "Error: This script requires 'sudo' privileges in order to write to disk & mount media."
-        exit 1
+	echo "Error: This script requires 'sudo' privileges in order to write to disk & mount media."
+	exit 1
 fi
 
 # check to make sure populated
 if [ "$MEDIA" = "" ] ; then
-        usage
-        exit 1
+	usage
+	exit 1
 fi
 
 # change cubietruck target to uppercase
 if [ "$TARGET" = "cubietruck" ]; then
-        TARGET="Cubietruck"
+	TARGET="Cubietruck"
 fi
 
 # check for boards
 if [ "$TARGET" != "" -a ! -e "${BOARDDIR}/${TARGET}" ] ; then
-        echo "Error: You must choose a supported board or none at all." 
-        usage
-        exit 1
+	echo "Error: You must choose a supported board or none at all." 
+	usage
+	exit 1
 fi
 
 # image exists
 if [ ! -f "$IMAGE" ] && [ "$IMAGE" != "" ] ; then
-        echo "Error: $IMAGE not found! Please choose an existing image."
-        exit 1
+	echo "Error: $IMAGE not found! Please choose an existing image."
+	exit 1
 fi
 
 # device exists
 if [ ! -e "$MEDIA" ] ; then
-        echo "Error: $MEDIA not found! Please choose an existing device."
-        exit 1
+	echo "Error: $MEDIA not found! Please choose an existing device."
+	exit 1
 fi
 
 clear
@@ -176,33 +176,33 @@ echo " "
 echo "====================================================="
 # Image if included
 if [ "$IMAGE" != "" ] ; then
-        echo "= Selected Image:                                 "
-        echo "= $IMAGE"
+	echo "= Selected Image:                                 "
+	echo "= $IMAGE"
 fi
 echo "= Selected Media : $MEDIA"
 # target hardware platform
 if [ "$TARGET" != "" ] ; then 
-        echo "= U-Boot Target : $TARGET"
+	echo "= U-Boot Target : $TARGET"
 fi
 # SE Linux On/Off
 if [ "$SELINUX" != "" ] ; then
-        echo "= SELINUX = $SELINUX"
+	echo "= SELINUX = $SELINUX"
 fi
 # Remove root password
 if [ "$NOROOTPASS" != "" ] ; then
-        echo "= Root Password will be removed."
+	echo "= Root Password will be removed."
 fi
 # Resize root filesystem to fill media device
 if [ "$RESIZEFS" != "" ] ; then
-        echo "= Root partition will be resized"
+	echo "= Root partition will be resized"
 fi
 # Console to be added
 if [ "$CONSOLE" != "" ] ; then
-        echo "= Console for $TARGET will be added."
+	echo "= Console for $TARGET will be added."
 fi
 # User ssh key
 if [ "$SSH_KEY" != "" ] ; then
-        echo "= SSH Public Key $SSH_KEY will be added."
+	echo "= SSH Public Key $SSH_KEY will be added."
 fi
 echo "====================================================="
 echo " "
@@ -212,78 +212,78 @@ echo "******** WARNING! ALL DATA WILL BE DESTROYED ********"
 echo "*****************************************************"
 echo "*****************************************************"
 if [ "$NOASK" != 1 ] ; then 
-        echo " "
-        echo " Type 'YES' to proceed, anything else to exit now "
-        echo " "
-        # wait for agreement
-        read -p "= Proceed? " PROCEED
-        if [ "$(echo ${PROCEED} | tr [:lower:] [:upper:])" != "YES" ] ; then
-                echo "User exit, no image written."
-                exit 0
-        fi
+	echo " "
+	echo " Type 'YES' to proceed, anything else to exit now "
+	echo " "
+	# wait for agreement
+	read -p "= Proceed? " PROCEED
+	if [ "$(echo ${PROCEED} | tr [:lower:] [:upper:])" != "YES" ] ; then
+		echo "User exit, no image written."
+		exit 0
+	fi
 fi
 # umount before starting
 umount $MEDIA* &> /dev/null
 
 # Write the disk image to media
 if [ "$IMAGE" != "" ] ; then
-        echo "= Writing: "
-        echo "= $IMAGE "
-        echo "= To: $MEDIA ...."
-        xzcat $IMAGE | dd of=$MEDIA bs=4M; sync; sleep 3
-        echo "= Writing image complete!"
-        # read the new partition table
-        partprobe "$MEDIA"
+	echo "= Writing: "
+	echo "= $IMAGE "
+	echo "= To: $MEDIA ...."
+	xzcat $IMAGE | dd of=$MEDIA bs=4M; sync; sleep 3
+	echo "= Writing image complete!"
+	# read the new partition table
+	partprobe "$MEDIA"
 fi
 # check to see how many partitions on the image
 partprobe "$MEDIA"
 sleep 1
 case $MEDIA in
-        "/dev/mmcblk"*)
-                if [ -e "$MEDIA"p4 ]; then
-                        export FIRMPART="${MEDIA}p1"
-                        BOOTPART="${MEDIA}p2"
-                        ROOTPART="${MEDIA}p4"
-                        PARTNUM=4
-                else
-                        BOOTPART="${MEDIA}p1"
-                        ROOTPART="${MEDIA}p3"
-                        PARTNUM=3
-                fi
-                ;;
-        *)
-                if [ -e "$MEDIA"4 ]; then
-                        export FIRMPART="${MEDIA}1"
-                        BOOTPART="${MEDIA}2"
-                        ROOTPART="${MEDIA}4"
-                        PARTNUM=4
-                else
-                        BOOTPART="${MEDIA}1"
-                        ROOTPART="${MEDIA}3"
-                        PARTNUM=3
-                fi
-                ;;
+	"/dev/mmcblk"*)
+		if [ -e "$MEDIA"p4 ]; then
+			export FIRMPART="${MEDIA}p1"
+			BOOTPART="${MEDIA}p2"
+			ROOTPART="${MEDIA}p4"
+			PARTNUM=4
+		else
+			BOOTPART="${MEDIA}p1"
+			ROOTPART="${MEDIA}p3"
+			PARTNUM=3
+		fi
+		;;
+	*)
+		if [ -e "$MEDIA"4 ]; then
+			export FIRMPART="${MEDIA}1"
+			BOOTPART="${MEDIA}2"
+			ROOTPART="${MEDIA}4"
+			PARTNUM=4
+		else
+			BOOTPART="${MEDIA}1"
+			ROOTPART="${MEDIA}3"
+			PARTNUM=3
+		fi
+		;;
 esac
 
 # resize root filesystem before mounting
 if [ "$RESIZEFS" != "" ] ; then
-        echo "= Resizing $MEDIA ...."
-        sync
+	echo "= Resizing $MEDIA ...."
+	sync
 	count=0
-        echo ", +" | sfdisk -N "$PARTNUM" "$MEDIA"
-        while [ $? != '0' ]; do
-                sleep 5
-                echo ", +" | sfdisk -N "$PARTNUM" "$MEDIA"
+	echo ", +" | sfdisk -N "$PARTNUM" "$MEDIA"
+	while [ $? != '0' ]; do
+		sleep 5
+		echo ", +" | sfdisk -N "$PARTNUM" "$MEDIA"
 		count=$((count+1))
 		if [ $count -gt 5 ]
 			then
 				echo "= Partition Resize Failed."
-		        	continue
+				continue
 		fi
 			
-        done
-        
-        partprobe "$MEDIA"
+	done
+	
+	partprobe "$MEDIA"
 
 	FS_TYPE=$(file -s "$ROOTPART" | awk '{print $3}')
 		if [ "$FS_TYPE" = "XFS" ]; then
@@ -294,7 +294,7 @@ if [ "$RESIZEFS" != "" ] ; then
 			umount "$ROOTPART"
 		else
 			fsck.ext4 -fy "$ROOTPART"
-        		resize2fs "$ROOTPART"
+			resize2fs "$ROOTPART"
 		fi
 fi
 
@@ -302,62 +302,62 @@ fi
 mkdir /tmp/{boot,root} &> /dev/null
 mount "$BOOTPART" /tmp/boot &> /dev/null
 if [ $? -ne 0 ]; then
-        echo "Error: mount $BOOTPART /tmp/boot failed"
-        exit 1
+	echo "Error: mount $BOOTPART /tmp/boot failed"
+	exit 1
 fi
 
 mount "$ROOTPART" /tmp/root &> /dev/null
 if [ $? -ne 0 ]; then
-        echo "Error: mount $ROOTPART /tmp/root failed"
-        exit 1
+	echo "Error: mount $ROOTPART /tmp/root failed"
+	exit 1
 fi
 
 # turn off selinux
 if [ "$SELINUX" != "" ] ; then
-        if [ "$(echo ${SELINUX} | tr [:lower:] [:upper:])" = "OFF" ] ; then
-                echo "= Turning SELinux off ..."
-                sed -i 's/append/& enforcing=0/' /tmp/boot/extlinux/extlinux.conf
-                # turn on selinux
-        elif [ "$(echo ${SELINUX} | tr [:lower:] [:upper:])" = "ON" ] ; then
-                echo "= Turning SELinux on ..."
-                sed -i 's/ enforcing=0//' /tmp/boot/extlinux/extlinux.conf
-        fi
+	if [ "$(echo ${SELINUX} | tr [:lower:] [:upper:])" = "OFF" ] ; then
+		echo "= Turning SELinux off ..."
+		sed -i 's/append/& enforcing=0/' /tmp/boot/extlinux/extlinux.conf
+		# turn on selinux
+	elif [ "$(echo ${SELINUX} | tr [:lower:] [:upper:])" = "ON" ] ; then
+		echo "= Turning SELinux on ..."
+		sed -i 's/ enforcing=0//' /tmp/boot/extlinux/extlinux.conf
+	fi
 fi
 # Remove root password
 if [ "$NOROOTPASS" = "1" ] ; then
-        echo "= Removing the root password."
-        sed -i 's/root:x:/root::/' /tmp/root/etc/passwd
+	echo "= Removing the root password."
+	sed -i 's/root:x:/root::/' /tmp/root/etc/passwd
 fi
 # Add ssh key to the image
 if [ "$SSH_KEY" != "" ] ; then
-        if [ -f $SSH_KEY ]; then
-                echo "= Adding SSH key to authorized keys."
-                mkdir /tmp/root/root/.ssh/ &> /dev/null
-                cat $SSH_KEY >> /tmp/root/root/.ssh/authorized_keys
-                chmod -R u=rwX,o=,g= /tmp/root/root/.ssh/
-        else
-                echo "= SSH key $SSH_KEY : Not Found!"
-                echo "= WARNING: No SSH Key Added."
-        fi
-        
+	if [ -f $SSH_KEY ]; then
+		echo "= Adding SSH key to authorized keys."
+		mkdir /tmp/root/root/.ssh/ &> /dev/null
+		cat $SSH_KEY >> /tmp/root/root/.ssh/authorized_keys
+		chmod -R u=rwX,o=,g= /tmp/root/root/.ssh/
+	else
+		echo "= SSH key $SSH_KEY : Not Found!"
+		echo "= WARNING: No SSH Key Added."
+	fi
+	
 fi
 # determine uboot and write to disk 
 if [ "$TARGET" = "" ]; then
-        echo "= No U-boot will be written."
-        TARGET="Mystery Board"
+	echo "= No U-boot will be written."
+	TARGET="Mystery Board"
 else
-        PREFIX=/tmp/root
-        . "${BOARDDIR}/${TARGET}"
-        # Add console
-        if [ "$CONSOLE" = "1" ] && [ "$SYSCON" != "" ] ; then
-                echo "= Adding console $SYSCON to extlinux.conf ..."
-                sed -i "s|append|& console=$SYSCON|" /tmp/boot/extlinux/extlinux.conf
+	PREFIX=/tmp/root
+	. "${BOARDDIR}/${TARGET}"
+	# Add console
+	if [ "$CONSOLE" = "1" ] && [ "$SYSCON" != "" ] ; then
+		echo "= Adding console $SYSCON to extlinux.conf ..."
+		sed -i "s|append|& console=$SYSCON|" /tmp/boot/extlinux/extlinux.conf
 		if [ "$TARGET" = "rpi2" ] || [ "$TARGET" = "rpi3" ]; then
-                        mkdir /tmp/fw &> /dev/null
-                        mount "$FIRMPART" /tmp/fw &> /dev/null
-                        sed -i "s|# enable_uart=1|enable_uart=1|" /tmp/fw/config.txt
-                fi
-        fi
+			mkdir /tmp/fw &> /dev/null
+			mount "$FIRMPART" /tmp/fw &> /dev/null
+			sed -i "s|# enable_uart=1|enable_uart=1|" /tmp/fw/config.txt
+		fi
+	fi
 
 fi
 # fix up rpi2/3
diff --git a/rpi-firmware-update b/rpi-firmware-update
--- a/rpi-firmware-update
+++ b/rpi-firmware-update
@@ -2,8 +2,8 @@
 
 # ensure sudo user
 if [ "$(whoami)" != "root" ] ; then
-        echo "Error: This script requires 'sudo' privileges in order to write to disk & mount media."
-        exit 1
+	echo "Error: This script requires 'sudo' privileges in order to write to disk & mount media."
+	exit 1
 fi
 
 echo
@@ -11,55 +11,55 @@ echo "= This will update U-Boot and the "
 echo "= Raspberry Pi Firmware to the latest."
 UBOOT=$(rpm -q uboot-images-armv7)
 if [ "$UBOOT" = "package uboot-images-armv7 is not installed" ]; then
-        echo
-        echo "$UBOOT"
-        read -p "Would you like to install uboot-images-armv7 (yes or no)? " INSTALL_UBOOT
-        if [ "$(echo ${INSTALL_UBOOT} | tr [:lower:] [:upper:])" = "YES" ] ; thee
+	echo
+	echo "$UBOOT"
+	read -p "Would you like to install uboot-images-armv7 (yes or no)? " INSTALL_UBOOT
+	if [ "$(echo ${INSTALL_UBOOT} | tr [:lower:] [:upper:])" = "YES" ] ; thee
 n
-        dnf install -y uboot-images-armv7
-        UBOOT=$(rpm -q uboot-images-armv7)
-        fi
+	dnf install -y uboot-images-armv7
+	UBOOT=$(rpm -q uboot-images-armv7)
+	fi
 fi
 FW=$(rpm -q bcm283x-firmware)
 if [ "$FW" = "package bcm283x-firmware is not installed" ]; then
-        echo
-        echo "$FW"
-        read -p "Would you like to install bcm283x-firmware (yes or no)? " INSTALL_FW
-        if [ "$(echo ${INSTALL_FW} | tr [:lower:] [:upper:])" = "YES" ] ; then
-                dnf install -y bcm283x-firmware
-                FW=$(rpm -q bcm283x-firmware)
-        fi
+	echo
+	echo "$FW"
+	read -p "Would you like to install bcm283x-firmware (yes or no)? " INSTALL_FW
+	if [ "$(echo ${INSTALL_FW} | tr [:lower:] [:upper:])" = "YES" ] ; then
+		dnf install -y bcm283x-firmware
+		FW=$(rpm -q bcm283x-firmware)
+	fi
 fi
 if [ "$FW" = "package bcm283x-firmware is not installed" ] && [ "$UBOOT" = "package uboot-images-armv7 is not installed" ]; then
-        echo
-        echo "Nothing to update, exiting."
-        exit 0
+	echo
+	echo "Nothing to update, exiting."
+	exit 0
 fi
 echo
 echo "= Uboot: $UBOOT"
 echo "= Firmware: $FW"
 if [ -d /boot/fw ]; then
-        	mount /dev/mmcblk0p1 /boot/fw
-        else
-        	mkdir /boot/fw
-        	mount /dev/mmcblk0p1 /boot/fw
+		mount /dev/mmcblk0p1 /boot/fw
+	else
+		mkdir /boot/fw
+		mount /dev/mmcblk0p1 /boot/fw
 fi
 # copy uboot
 if [ -f /usr/share/uboot/rpi_2/u-boot.bin ]; then
-        cp -rp /usr/share/uboot/rpi_2/u-boot.bin /boot/fw/rpi2-u-boot.bin
-        else
-        echo "Missing U-Boot for Raspberry Pi 2, no file copied."
+	cp -rp /usr/share/uboot/rpi_2/u-boot.bin /boot/fw/rpi2-u-boot.bin
+	else
+	echo "Missing U-Boot for Raspberry Pi 2, no file copied."
 fi
 if [ -f /usr/share/uboot/rpi_3_32b/u-boot.bin ]; then
-        cp -rp /usr/share/uboot/rpi_3_32b/u-boot.bin /boot/fw/rpi3-u-boot.bin
-        else
-        echo "Missing U-Boot for Raspberry Pi 3, no file copied."
+	cp -rp /usr/share/uboot/rpi_3_32b/u-boot.bin /boot/fw/rpi3-u-boot.bin
+	else
+	echo "Missing U-Boot for Raspberry Pi 3, no file copied."
 fi
 # copy fw
 if [ -d /usr/share/bcm283x-firmware ]; then
-        cp -rfp /usr/share/bcm283x-firmware/*.{bin,dat,elf} /boot/fw/
+	cp -rfp /usr/share/bcm283x-firmware/*.{bin,dat,elf} /boot/fw/
 else
-        echo "Missing bcm283x-firmware, no files copied."
+	echo "Missing bcm283x-firmware, no files copied."
 fi
 umount /boot/fw
 echo 
diff --git a/update-uboot b/update-uboot
--- a/update-uboot
+++ b/update-uboot
@@ -22,100 +22,100 @@ For list of supported boards please check SUPPORTED-BOARDS file.
 
 # check the args
 while [ $# -gt 0 ]; do
-        case $1 in
-                --debug)
-                        set -x
-                        ;;
-                -h|--help)
-                        usage
-                        ;;
-                --target*)
-                        if echo $1 | grep '=' >/dev/null ; then
-                                TARGET=$(echo $1 | sed 's/^--target=//')
-                        else
-                                TARGET=$2
-                                shift
-                        fi
-                        ;;
-                --media*)
-                        if echo $1 | grep '=' >/dev/null ; then
-                                MEDIA=$(echo $1 | sed 's/^--media=//')
-                        else
-                                MEDIA=$2
-                                shift
-                        fi
-                        ;;
-                --tag*)
-                        if echo $1 | grep '=' >/dev/null ; then
-                                KOJI_TAG=$(echo $1 | sed 's/^--tag=//')
-                        else
-                                KOJI_TAG=$2
-                                shift
-                        fi
-                        ;;
-                *)
-                        echo "$(basename ${0}): Error - ${1}"
-                        usage
-                        exit 1
-                        ;;
-        esac
-        shift
+	case $1 in
+		--debug)
+			set -x
+			;;
+		-h|--help)
+			usage
+			;;
+		--target*)
+			if echo $1 | grep '=' >/dev/null ; then
+				TARGET=$(echo $1 | sed 's/^--target=//')
+			else
+				TARGET=$2
+				shift
+			fi
+			;;
+		--media*)
+			if echo $1 | grep '=' >/dev/null ; then
+				MEDIA=$(echo $1 | sed 's/^--media=//')
+			else
+				MEDIA=$2
+				shift
+			fi
+			;;
+		--tag*)
+			if echo $1 | grep '=' >/dev/null ; then
+				KOJI_TAG=$(echo $1 | sed 's/^--tag=//')
+			else
+				KOJI_TAG=$2
+				shift
+			fi
+			;;
+		*)
+			echo "$(basename ${0}): Error - ${1}"
+			usage
+			exit 1
+			;;
+	esac
+	shift
 done
 
 if [ -d "/usr/share/arm-image-installer/boards.d" ]; then
-        BOARDDIR="/usr/share/arm-image-installer/boards.d"
+	BOARDDIR="/usr/share/arm-image-installer/boards.d"
 else
-        DIR=$(dirname $0)
-        BOARDDIR="${DIR}/boards.d"
+	DIR=$(dirname $0)
+	BOARDDIR="${DIR}/boards.d"
 fi
 # ensure sudo user
 if [ "$(whoami)" != "root" ] ; then
-        echo "Error: This script requires 'sudo' privileges in order to write to disk & mount media."
-        exit 1
+	echo "Error: This script requires 'sudo' privileges in order to write to disk & mount media."
+	exit 1
 fi
 
 # check if media exists
 if [[ ! -e $MEDIA ]] ; then
-        echo "Missing media"
-        usage
-        exit 1
+	echo "Missing media"
+	usage
+	exit 1
 fi
 
 if [[ $TARGET = '' ]] ; then
-        echo "Missing target"
-        usage
-        exit 1
+	echo "Missing target"
+	usage
+	exit 1
 fi
 if [[ $KOJI_TAG != '' ]] ; then
-        if [[ ! -f /usr/bin/koji ]]; then
-                echo "Please install koji-utils for this option."
-                exit 1
-        else
-                PREFIX='/tmp/root/'
-                rm -rf /tmp/root &> /dev/null
-                mkdir $PREFIX
+	if [[ ! -f /usr/bin/koji ]]; then
+		echo "Please install koji-utils for this option."
+		exit 1
+	else
+		PREFIX='/tmp/root/'
+		rm -rf /tmp/root &> /dev/null
+		mkdir $PREFIX
 
-                #get the latest uboot
-                pushd $PREFIX &> /dev/null
-                if [ $KOJI_TAG = f22 ]; then
-                        koji download-build --arch=armv7hl --latestfrom=$KOJI_TAG uboot-tools
-                else
-                        koji download-build --arch=noarch --latestfrom=$KOJI_TAG uboot-tools
-                fi
-                # unpack uboot
-                for rpm in uboot-images*.rpm
-                do
-                        rpm2cpio "${rpm}" | cpio -idv &> /dev/null
-                done
-                popd &> /dev/null
-        fi
+		#get the latest uboot
+		pushd $PREFIX &> /dev/null
+		if [ $KOJI_TAG = f22 ]; then
+			koji download-build --arch=armv7hl --latestfrom=$KOJI_TAG uboot-tools
+		else
+			koji download-build --arch=noarch --latestfrom=$KOJI_TAG uboot-tools
+		fi
+		# unpack uboot
+		for rpm in uboot-images*.rpm
+		do
+			rpm2cpio "${rpm}" | cpio -idv &> /dev/null
+		done
+		popd &> /dev/null
+	fi
 fi
 # determine uboot and write to disk 
 if [ "$TARGET" = "" ]; then
-        echo "= No U-boot will be written."
-        TARGET="Mystery Board"
+	echo "= No U-boot will be written."
+	TARGET="Mystery Board"
 else
-        . "${DIR}/${BOARDDIR}/${TARGET}"
+	. "${DIR}/${BOARDDIR}/${TARGET}"
 fi
 
 echo "= Complete!"
