create-install-media: make sure we run under sudo and drop sudo use
We follow arm-image-installer way of handling sudo.

diff --git a/create-install-media b/create-install-media
--- a/create-install-media
+++ b/create-install-media
@@ -48,6 +48,12 @@ while [ $# -gt 0 ]; do
         shift
 done
 
+# ensure user
+if [ "$(sudo whoami)" != "root" ] ; then
+        echo "Error: This script requires 'sudo' privileges in order to write to disk & mount media."
+        exit 1
+fi
+
 # check if media exists
 if [[ ! -e $MEDIA ]] ; then 
         echo "Missing media"
@@ -61,15 +67,15 @@ fi
 
 # unmount media
 echo "= Umounting $MEDIA."
-sudo umount $MEDIA* &> /dev/null
+umount $MEDIA* &> /dev/null
 
 # create partition 
 echo "= Creating partition."
-sudo parted -s $MEDIA mklabel msdos &> /dev/null
-sudo parted -s -a optimal $MEDIA mkpart primary ext4 1 512 &> /dev/null
+parted -s $MEDIA mklabel msdos &> /dev/null
+parted -s -a optimal $MEDIA mkpart primary ext4 1 512 &> /dev/null
 
 # re-read table
-sudo partprobe $MEDIA
+partprobe $MEDIA
 
 # check media type /dev/sdX or /dev/mmcblkX
 case $MEDIA in
@@ -83,19 +89,19 @@ esac
 
 # create filesystem
 echo "= Creating filesystem."
-sudo mkfs.ext4 $PART1 &> /dev/null
+mkfs.ext4 $PART1 &> /dev/null
 
 # create temp dir
 echo "= Making temporary directory."
-sudo rm -rf /tmp/install-card
+rm -rf /tmp/install-card
 mkdir /tmp/install-card
-sudo mount $PART1 /tmp/install-card
+mount $PART1 /tmp/install-card
 
 # get pxe images and dtb files
-sudo /usr/bin/rsync -ahH rsync://dl.fedoraproject.org/pub/fedora/linux/releases/22/Server/armhfp/os/images/pxeboot/ /tmp/install-card/
+/usr/bin/rsync -ahH rsync://dl.fedoraproject.org/pub/fedora/linux/releases/22/Server/armhfp/os/images/pxeboot/ /tmp/install-card/
 
 # make and populate the extlinux.conf
-sudo mkdir /tmp/install-card/extlinux/
+mkdir /tmp/install-card/extlinux/
 cat > /tmp/extlinux.conf << EOF
 # extlinux.conf generated by script
 ui menu.c32
@@ -111,9 +117,9 @@ append inst.repo=$URL
 fdtdir /dtb/
 initrd /initrd.img
 EOF
-sudo mv /tmp/extlinux.conf /tmp/install-card/extlinux/
+mv /tmp/extlinux.conf /tmp/install-card/extlinux/
 sync
-sudo umount $MEDIA* &> /dev/null
+umount $MEDIA* &> /dev/null
 echo "= Complete!"
 
 # vi: tabstop=8 softtabstop=0 expandtab shiftwidth=8 smarttab
