Add sudo check to rpi script.

diff --git a/rpi-uboot-update b/rpi-uboot-update
--- a/rpi-uboot-update
+++ b/rpi-uboot-update
@@ -1,5 +1,11 @@
 #!/bin/bash
 
+# ensure sudo user
+if [ "$(whoami)" != "root" ] ; then
+        echo "Error: This script requires 'sudo' privileges in order to write to disk & mount media."
+        exit 1
+fi
+
 echo
 echo "= This will update U-Boot and the "
 echo "= Raspberry Pi Firmware to the latest."
