Remove sudo from boards.d and update-uboot.

diff --git a/update-uboot b/update-uboot
--- a/update-uboot
+++ b/update-uboot
@@ -69,6 +69,12 @@ else
         BOARDDIR="${DIR}/boards.d"
 fi
 
+# ensure sudo user
+if [ "$(whoami)" != "root" ] ; then
+        echo "Error: This script requires 'sudo' privileges in order to write to disk & mount media."
+        exit 1
+fi
+
 # check if media exists
 if [[ ! -e $MEDIA ]] ; then
         echo "Missing media"
