Removed uneeded sudo from update uboot.

diff --git a/update-uboot b/update-uboot
--- a/update-uboot
+++ b/update-uboot
@@ -68,6 +68,11 @@ else
         DIR=$(dirname $0)
         BOARDDIR="${DIR}/boards.d"
 fi
+# ensure sudo user
+if [ "$(whoami)" != "root" ] ; then
+        echo "Error: This script requires 'sudo' privileges in order to write to disk & mount media."
+        exit 1
+fi
 
 # check if media exists
 if [[ ! -e $MEDIA ]] ; then
@@ -87,7 +92,7 @@ if [[ $KOJI_TAG != '' ]] ; then
                 exit 1
         else
                 PREFIX='/tmp/root/'
-                sudo rm -rf /tmp/root &> /dev/null
+                rm -rf /tmp/root &> /dev/null
                 mkdir $PREFIX
 
                 #get the latest uboot
